name: shop
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^0.13.4
  carousel_slider: ^5.0.0
  flutter_widget_from_html: ^0.15.2
  photo_view: ^0.15.0
  shared_preferences: ^2.0.0
  lottie: ^2.2.0
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/splash_animation.json
    - assets/lottie/loading_animation.json

  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/custom_font_x.ttf
          weight: 700
